### PR TITLE
Hooked up Code Search to Frontend for Condition and Encounter Filter Code Autocomplete

### PR DESCRIPTION
**Pull request by noranda**
# Hooked up Code Search to Frontend for Condition and Encounter Filter Code Autocomplete
- Removed sample codes.
- Reduced delay of Bootstrap 3 typeahead.
- Hooked up to autocomplete UI to code search on the backend using the `/CodeLookup` endpoint.
##### TODO:
- [ ] Modify backend code search to only return codes attached to existing conditions and encounters.
- [ ] Write tests.

### CODE REVIEW

**Comment by cmoesel** [comment]
Regarding the _TODO_: Do we really only want to allow codes that are being used?  It seems that perhaps someone might want to set up a filter for a code even if no one has it yet?  Or do you think that's unlikely?  I'm just thinking out loud here...

**Comment by noranda** [comment]
This is a good question for the end user. Perhaps we can compromise by prioritizing the full list by codes that exist. We can also increase the limit if we need to, but I don't want it too long. For the purposes of this PR, it's good to go, but I'll add a comment to the _TODO_ story about this discussion.

**Comment by ghost** [comment]
We could have the codelookup service return a count of existing instances of each matching code which could then be used to prioritize the ordering of the auto complete list, if that would be useful. I agree with Noranda that this is a good question for the users.

**Comment by noranda** [comment]
Alternatively, I can look into having the dropdown list scroll, although I'm not sure at this moment how easy that would be to implement. Let's bench this discussion for later.

**Comment by noranda** [comment]
@ahubley and @cmoesel: Added these comments to the appropriate pivotal story.
@schreiaj: This PR is ready for your review and merge.

**Pull request merged**
