### PR TITLE
Remote Patient Search

### PR DESCRIPTION
**Pull request by schreiaj**
Removed sorted and filtered patients as all sorting and filtering is now down on the backend

Made patient search box query remote store instead of local store.

### CODE REVIEW

**Comment by noranda** [comment]
@schreiaj: I'm getting the following error during testing: `patient-badge.js:26 Uncaught TypeError: Cannot read property 'value' of undefined`. There are also a ton of deprecation warnings that is slowing the search down.

In addition, the behavior isn't working as expected. When typing a name in, the search filters on change properly, but when a character is deleted, the total count updates without rendering the added patients.

pr-patient-search

**Comment by noranda** [comment]
@schreiaj: In addition, you may want to use a [debounce](http://emberjs.com/api/classes/Ember.run.html#method_debounce) method to delay the patient search observer slightly. That should make the user experience better.

**Comment by schreiaj** [comment]
Running locally I see a small handful of deprecations all of which are related to code in the FHIR-adapter models. I get no new deprecations when loading patients. 

Additionally, when backspacing it works fine in all of my testing. I don't see any of those `cannot read property of 'value'` messages unless the server 500's are you sure that's not causing it? 

patient-search-backspace
I'll add debounce but I am unable to replicate the other issues.

**Comment by cmoesel** [comment]
I've tried this branch out, per Andrew's request.  When trying the branch as-is, I did see the errors: `patient-badge.js:26 Uncaught TypeError: Cannot read property 'value' of undefined`.  That said, I recognized it as an error that I fixed in Noranda's _na-risk-assessment_ branch (now merged to master).

I also managed to get it into a state where there was other really funky behavior -- such as an inconsistent number of records on each page (6 on page 1, 11 on page 2, etc).

I rebased this branch on top of _master_ (to pull in that bug fix), and that seems to have cleared the initial error _and_ the funkiness, but now I get a different error:

```
ember.debug.js:688 Uncaught TypeError: Cannot read property 'apply' of undefined
    Backburner.run @ ember.debug.js:688
    (anonymous function) @ ember.debug.js:992
```

Perhaps the new one is related to my fix in the other branch?  I don't know.  ([This was my fix](https://github.com/intervention-engine/frontend/commit/e85f8a71ba2eef96fc0406565b472f394d070d47) if you want to check it out -- it's mainly to handle the situation of a patient who doesn't have the selected risk assessment, but _does_ have other risk assessment types).  Despite the error, I was _not_ able to get the app into a funky state -- from the user perspective, it all appeared as if it was working (filtering worked correctly, paging worked correctly, etc).

I did find one small bug. If you select a patient, then it goes into the patient view and the patient nav link(`1/99 >`) works to navigate through the filtered list, but the `Back to Patient List` link brings you back to the _unfiltered_ list.  I'm OK with filing this as a separate bug.  It would be nice, however, to see if we can figure out what that ember error is.

**Comment by noranda** [comment]
@schreiaj: I tried this out again with the branch rebased to `master` and I get the same results as @cmoesel. The behavior looks good now, but there is one remaining error: `Uncaught TypeError: Cannot read property 'apply' of undefined`. It appears to be ember-data related.

**Comment by schreiaj** [comment]
Interestingly, it wasn't Ember Data related at all. It was related to the debouncing code attempting to call `this.refetch()` and then using the return value of that as the function for debouncing. Which explains why it appeared to be working when, in reality, the debouncing wasn't doing anything (because `refetch` was called all the time.

**Pull request merged**
