### PR TITLE
ER Visits on Wheel 

### PR DESCRIPTION
**Pull request by schreiaj**
Added mixins for determining if a thing has a code (codeable) and for if a thing happened within a date range or in the future (dateable).

Added emergencyRoomAdmissions to the patient and the wheel

Refactored 30-day readmissions to use the new mixin

Refactored Inpatient Admissions to use the new mixin

### CODE REVIEW

**Comment by cmoesel** [comment]
The notifications code I just wrote also needs to detect inpatient admissions, re-admissions, and ER visits.  It looks like we're a bit inconsistent.  For the most part, it seems we're just using different codes and code systems.  The right answer is probably the union of them for each encounter type.

For re-admissions, however, I'm using an SCT code to detect it and you're using a timing relationship.  Technically, using a code is a better approach because a second admission in 30 days might be for a different reason (so it wouldn't really be considered a re-admission).  That said, if the encounters aren't coded properly as re-admissions then the timing relationship can be a decent approximation.  We should look at the data and see what's there.

You can see the codes I'm using here: https://github.com/intervention-engine/ie/blob/master/notifications/encounter_type_notification.go#L67

**Comment by cmoesel** [comment]
Almost forgot to mention... given that the front-end and back-end should be in sync on the codes used to categorize encounter types, should the ie server provide those mappings via HTTP?  Then instead of hard-coding them in the front-end, you retrieve (and cache) them from the server? Or perhaps the task of categorization shouldn't be done in the front end at all?  But instead it receives the categorized events from the server?

Today was the first day I ever looked at the frontend though, so feel free to tell me that I'm speaking nonsense.

**Comment by schreiaj** [comment]
It does make sense to make these codes configurable somehow. I'm not sure what the best approach is to do that.  I will say, having looked at that code and knowing what it's going to end up looking like on the front end, I think that we do need to have some notion of valuesets. Naive approach would be to bundle them as a JSON file and add another function to `codeable` to check if the code is in a value set. 

There's also the 60 day ER admission window (which is frankly an arbitrary number) that should likely be configurable somehow.

**Comment by cmoesel** [comment]
Good thought regarding the value sets.  We could store the value sets on the server -- since FHIR has a ValueSet resource.  We'd still need a static JSON file to init the server, but the UI would always just grab it from the server.  This would also allow the value set to be easily customized at other sites that might use proprietary codes not in our stock value set definition.

Anyway-- I was just bringing it up.  I don't think this discussion should hold up the PR -- it's just something to consider post-PR.

**Pull request merged**
